run:
  timeout: 60m
  go: 1.17

issues:
  exclude-rules:
    - linters:
        - gosimple
      text: "S1034"

  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - errcheck
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - unparam
    - varcheck
    - vet
    - vetshadow

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close,io:WriteString
  nakedret:
    max-func-lines: 40
