#!/bin/bash
#
# This script helps new contributors set up their local workstation for
# gcorecloud development and contributions.

# Create the environment
export GOPATH=$HOME/go
mkdir -p "${GOPATH}"

# Download gcorecloud into that environment
go get bitbucket.gcore.lu/gcloud/gcorecloud-go
cd "${GOPATH}/src/bitbucket.gcore.lu/gcloud/gcorecloud-go" || exit 1
git checkout master

# Write out the env.sh convenience file.
cd "${GOPATH}" || exit 1
cat <<EOF >env.sh
#!/bin/bash
export GOPATH=$(pwd)
export GOPHERCLOUD=$GOPATH/src/bitbucket.gcore.lu/gcloud/gcorecloud-go
EOF
chmod a+x env.sh

# Make changes immediately available as a convenience.
. ./env.sh
